name: ai_book_writing_platform
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_core_web: ^2.17.5
  firebase_auth_web: ^5.12.6
  cloud_firestore_web: ^4.1.2
  http: ^0.13.3
 # flutter_quill: ^7.3.2
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  firebase_storage: ^12.2.0
  image_picker: ^1.0.4
  fl_chart: ^0.63.0 
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.12
  provider: ^6.0.5
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
 
    - assets/images/placeholder.png
    - assets/images/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png