name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: stable

      - name: Install Dart SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install apt-transport-https
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main" > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update -y
          sudo apt-get install dart=3.5.0-1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

